export const SEARCH_PHOTOS = 'SEARCH_PHOTOS';

export const MODAL_PHOTO_OPEN = 'MODAL_PHOTO_OPEN';

export const MODAL_PHOTO_CLOSE = 'MODAL_PHOTO_CLOSE';

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';

export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';