export const SEARCH_PHOTOS = 'SEARCH_PHOTOS';

export const MODAL_PHOTO_OPEN = 'MODAL_PHOTO_OPEN';

export const MODAL_PHOTO_CLOSE = 'MODAL_PHOTO_CLOSE';

// Actions for App

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';

export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';

export const GENERIC_MODAL_OPEN = 'GENERIC_MODAL_OPEN';

export const GENERIC_MODAL_CLOSE = 'GENERIC_MODAL_CLOSE';

export const GENERIC_DIALOG_OPEN = 'GENERIC_DIALOG_OPEN';

export const GENERIC_DIALOG_CLOSE = 'GENERIC_DIALOG_CLOSE';

// Actions for Photo list

export const ADD_TO_PERSONAL_LIST = 'ADD_TO_PERSONAL_LIST';

export const REMOVE_FROM_PERSONAL_LIST = 'REMOVE_FROM_PERSONAL_LIST';

export const FETCH_PHOTOS = 'FETCH_PHOTOS';

export const ERROR_STATUS = 'ERROR_STATUS';

